version: '3'
services:
    petclinic:
        image: egapm/petclinic:pc-latest
        build:
            context: ../
        container_name: petclinic
        ports:
        - "8080:8080"
        networks:
        - testnet
        environment:
        - JAVA_OPTS="-javaagent:/opt/egbtm/eg_btm.jar"
        volumes:
        - /opt/egbtm:/opt/egbtm

networks:
  testnet:

